language: csharp
mono: none
dist: xenial
dotnet: 3.1
solution: OffTheRecord/OffTheRecord.sln

script:
 - dotnet build OffTheRecord/OffTheRecord.sln
 - dotnet test OffTheRecord/OffTheRecord.sln --logger "trx;LogFileName=testresults.trx" --collect:"XPlat Code Coverage"
  
notifications:
  email:
    recipients:
      - $emailaddress
    on_success: always # default: change
    on_failure: always # default: always