 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout
      - run: 
          name: Building solution
          command:
            dotnet build OffTheRecord/OffTheRecord.sln
      - run:
          name: Run tests and code coverage
          command:
            dotnet test OffTheRecord/OffTheRecord.sln --logger "trx;LogFileName=testresults.trx" --collect:"XPlat Code Coverage --settings OffTheRecord/coverlet.runsettings"
      - run:
          name: Install coveralls tool
          command:
            dotnet tool install --global coveralls.netcore --version 2.0.0
      - run:
          name: Update PATH
          command:
            export PATH="$PATH:/root/.dotnet/tools"
      - run: 
          name: Upload code coverage results to coverall.io
          command:
            coveralls.net --version -r $COVERALLIO