 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout
      - run: 
        name: Building solution
        command:
          dotnet build OffTheRecord/OffTheRecord.sln
      - run:
        name: Run tests and code coverage
        command:
          dotnet test OffTheRecord/OffTheRecord.sln --logger "trx;LogFileName=testresults.trx" --collect:"XPlat Code Coverage"