 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    
     steps:
       - checkout
       - run:
          name: Restore packages
          command:
            dotnet restore
       - run: 
          name: Building solution
          command:
            dotnet build OffTheRecord/OffTheRecord.sln
